os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
install: pip install flake8 pytest
before_script: flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
script: pytest -k "not fuzz"
